# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core
# Automatically detects solution file in nested folders

trigger:
  branches:
    include:
      - master

pool: Default

variables:
  configuration: 'Release'
  dotnetVersion: '7.0.x'  # LTS version

stages:
  - stage: Restore
    jobs:
      - job: RestoreJob
        steps:
          # Install supported .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'

          # Checkout repo
          - checkout: self
            clean: true

          # Find solution file dynamically (Windows agent)
          - powershell: |
              $sln = Get-ChildItem -Path "$(Build.SourcesDirectory)" -Recurse -Filter *.sln | Select-Object -First 1
              if ($null -eq $sln) { Write-Error "No .sln file found!" }
              Write-Host "Solution found: $($sln.FullName)"
              Write-Host "##vso[task.setvariable variable=SolutionPath]$($sln.FullName)"
            displayName: 'Find solution file'

          # Restore solution
          - task: DotNetCoreCLI@2
            displayName: 'Restore solution'
            inputs:
              command: 'restore'
              projects: '$(SolutionPath)'

  - stage: Build
    dependsOn: Restore
    jobs:
      - job: BuildJob
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Build solution'
            inputs:
              command: 'build'
              projects: '$(SolutionPath)'
              arguments: '--configuration $(configuration)'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Run tests'
            inputs:
              command: 'test'
              projects: '$(SolutionPath)'
              arguments: '--configuration $(configuration) --no-build'
