# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master

pool: Default

variables:
  configuration: 'Release'
  dotnetVersion: '9.0.x'  # LTS version supported on hosted agents

stages:
  - stage: Restore
    jobs:
      - job: RestoreJob
        steps:
          # Install supported .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '$(dotnetVersion)'

          # Checkout repo
          - checkout: self
            clean: true

          # Restore the nested solution
          - task: DotNetCoreCLI@2
            displayName: 'Restore solution'
            inputs:
              command: 'restore'
              projects: 'src/BTM.Products.Service/src/api/*.sln'

  - stage: Build
    dependsOn: Restore
    jobs:
      - job: BuildJob
        steps:
          # Build the nested solution
          - task: DotNetCoreCLI@2
            displayName: 'Build solution'
            inputs:
              command: 'build'
              projects: 'src/BTM.Products.Service/src/api/*.sln'
              arguments: '--configuration $(configuration)'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          # Run tests for the nested solution
          - task: DotNetCoreCLI@2
            displayName: 'Run tests'
            inputs:
              command: 'test'
              projects: 'src/BTM.Products.Service/src/api/*.sln'
              arguments: '--configuration $(configuration) --no-build'
