# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master

pool: Default

variables:
  configuration: 'Release'

stages:
  - stage: Restore
    jobs:
      - job: RestoreJob
        steps:
          # Install .NET SDK
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'

          # Checkout repo
          - checkout: self
            clean: true

          # Restore all solutions
          - task: DotNetCoreCLI@2
            displayName: 'Restore all solutions'
            inputs:
              command: 'restore'
              projects: '**/*.sln'

  - stage: Build
    dependsOn: Restore
    jobs:
      - job: BuildJob
        steps:
          # Build all solutions
          - task: DotNetCoreCLI@2
            displayName: 'Build all solutions'
            inputs:
              command: 'build'
              projects: '**/*.sln'
              arguments: '--configuration $(configuration)'

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          # Test all solutions
          - task: DotNetCoreCLI@2
            displayName: 'Run tests for all solutions'
            inputs:
              command: 'test'
              projects: '**/*.sln'
              arguments: '--configuration $(configuration) --no-build'

