version: '3.8'

volumes:
  sql_data:
services:
  btm.products.api:
    build:
        context: .
        dockerfile: BTM.Products.Api/Dockerfile
    image: ${DOCKER_REGISTRY-}btmproductsapi
    container_name: products-api
    ports:
     - "5002:80"     # HTTP
     - "5003:443"    # HTTPS

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=BTM.Product.Database;User Id=sa;Password=Password@123;Encrypt=True;TrustServerCertificate=True"
    volumes:
      - ./data/keys:/app/keys
    networks:
      - docker-network

networks:
  docker-network:
    external: true