version: '3.8'

services:
  btm.products.api:
    build:
        context: .
        dockerfile: BTM.Products.Api/Dockerfile
    image: ${DOCKER_REGISTRY-}btmproductsapi
    ports:
     - "5002:80"     # HTTP
     - "5003:443"    # HTTPS
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "Password@123"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/productsapi.pfx"
      ConnectionStrings__DefaultConnection: "Server=host.docker.internal,1433;Database=BTM.Product.Database;User Id=sa;Password=Password@123;Encrypt=True;TrustServerCertificate=True"
    volumes:
      - ./BTM.Products.Api/certs:/https:ro
      - ./data/keys:/app/keys

volumes:
  sql_data: